sonar.projectKey=demo
sonar.projectName=Demo Project
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.host.url=http://localhost:9000
sonar.token=squ_cc65d8552f187448d4408411b7665a0052b3e81f
